# Generated by Django 5.2.5 on 2025-08-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone_no', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('full_address', models.TextField(verbose_name='Full Address')),
                ('strand', models.CharField(max_length=100, verbose_name='Strand/Track')),
                ('section', models.CharField(max_length=50, verbose_name='Section')),
                ('school', models.CharField(max_length=200, verbose_name='School')),
                ('guardian_phone', models.CharField(max_length=20, verbose_name='Guardian Phone Number')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
