# Generated by Django 5.2.5 on 2025-08-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(choices=[('HUMMS', 'HUMMS'), ('STEM', 'STEM'), ('TVL', 'TVL'), ('ABM', 'ABM'), ('GAS', 'GAS')], max_length=10, verbose_name='Strand/Track'),
        ),
    ]
