# Generated by Django 5.2.5 on 2025-08-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_student_strand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(choices=[('HUMMS', 'HUMMS'), ('STEM', 'STEM'), ('TVL', 'TVL'), ('ABM', 'ABM'), ('GAS', 'GAS'), ('SAND', 'SAND'), ('ICT', 'ICT'), ('SPORTS', 'SPORTS')], max_length=10, verbose_name='Strand/Track'),
        ),
    ]
